export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_LOADING = 'SEARCH_USER_LOADING';
export const SEARCH_USER_FAILED = 'SEARCH_USER_FAILED';
export const ADD_EVENT = 'ADD_EVENT';
export const DISPASH_EVENT = 'DISPASH_EVENT';
